global:
  edpName: ""
  platform: "openshift"
  admins:
    - "stub_user_one@example.com"
  dnsWildCard:

name: nexus-operator
image:
  name: epamedp/nexus-operator
  version: v2.4.0

nexus:
  deploy: true
  name: "nexus"
  image: "sonatype/nexus3"
  version: "3.24.0"