name: nexus-operator
namespace: ""
platform: "openshift"
image:
  name: epamedp/nexus-operator
  version: v2.3.0

nexus:
  deploy: true
  name: "nexus"
  image: "sonatype/nexus3"
  version: "3.21.2"
  dnsWildCard: ""
  admins:
    - "userOne"
    - "userTwo"